appName: adservice
containerPort: 9555
imageName: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
imageVersion: v0.10.1
containerEnv:
  - envName: PORT
    envValue: "9555"

servicePort: 9555
